# Generated by Django 4.2.6 on 2024-02-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
