# Generated by Django 4.2.6 on 2024-02-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalQuestionaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
