# Generated by Django 4.2.6 on 2024-02-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0002_criticalquestionaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='questionnaire_type',
            field=models.CharField(blank=True, choices=[('regular', 'Regular Questionnaire'), ('critical', 'Critical Questionnaire')], max_length=10, null=True),
        ),
    ]
