# Generated by Django 4.2.6 on 2024-02-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0003_questionnaire_questionnaire_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='questionnaire_type',
            field=models.CharField(blank=True, choices=[('test1', 'Regular Questionnaire'), ('test2', 'Critical Questionnaire')], max_length=10, null=True),
        ),
    ]
