# Generated by Django 4.2.6 on 2023-12-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponses',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
