# Generated by Django 4.2.6 on 2023-12-08 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0001_initial'),
        ('responsemanagement', '0002_studentresponses_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponses',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionaire.questionnaire'),
        ),
    ]
