# Generated by Django 4.2.6 on 2023-12-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsemanagement', '0003_studentresponses_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelresponse',
            name='answer',
            field=models.TextField(),
        ),
    ]
