# Generated by Django 4.2.6 on 2023-12-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsemanagement', '0004_alter_modelresponse_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelresponse',
            name='total',
            field=models.IntegerField(default=69),
        ),
    ]
