# Generated by Django 4.2.6 on 2024-02-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsemanagement', '0006_alter_studentresponses_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelresponse',
            name='testType',
            field=models.CharField(default='test1', max_length=255),
        ),
        migrations.AddField(
            model_name='studentresponses',
            name='testType',
            field=models.CharField(default='test1', max_length=255),
        ),
    ]
